### ISSUE TITLE
Creating job and jobtype migrations from UML

### ISSUE THREAD

**Issue by haileydennis** [Simponic/cs3450-team-one#34]
Create migrations for job and jobtype schema, adding a one-to-one relation between job and jobtype

Estimated Time: 3 hours

**Comment by Simponic** [comment]
Just realized that instead of a one-to-many relation, I think we could stick to the requirements and have a job only have one type.

**Comment by Simponic** [comment]
Also, make sure the migrations/models end up in their own app folder with `python3 manage.py startapp`
